helm:
  parameters:
  - name: image.name
    value: docker.io/pashik/test2
    forcestring: true
  - name: image.tag
    value: latest@sha256:8a05b735d5bb0474bdb822bedaca4447880a96703920b29b7270a691a3bff881
    forcestring: true
