helm:
  parameters:
  - name: image.name
    value: docker.io/pashik/test2
    forcestring: true
  - name: image.tag
    value: latest@sha256:62d56b20b522cf006b76a6b8cd47439995eaa983bba19efbfc69dff6918dc018
    forcestring: true
