helm:
  parameters:
  - name: image.name
    value: docker.io/pashik/test2
    forcestring: true
  - name: image.tag
    value: latest@sha256:2d71914085ec723d5f9627ae16d2c664af8a4ba0bb86a6cfb9a5a80e11a9f1c3
    forcestring: true
