helm:
  parameters:
  - name: image.name
    value: docker.io/pashik/test2
    forcestring: true
  - name: image.tag
    value: latest@sha256:79b4d24b7fb0d0ed8d9c8420d351ee7f2fe9541f2b6015f24aabf5dab7155cf4
    forcestring: true
