apiVersion: apps/v1
kind: Deployment
metadata:
   name: test-deployment
   labels:
     name: test-deployment
   annotations:
    argocd-image-updater.argoproj.io/image-list: myimage=pashik/test2:latest
    argocd-image-updater.argoproj.io/myimage.update-strategy: digest
    #argocd-image-updater.argoproj.io/write-back-method: <argocd>
    # argocd or git
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/github-token
    # add git credentials secret named git-creds
    #argocd-image-updater.argoproj.io/git-branch: HEAD
    # Specifying a branch to commit to
spec:
   replicas: 2
   selector:
     matchLabels:
       app: test
   template:
     metadata:
       labels:
         app: test
     spec:
       containers:
       - name: test-argo
         image: pashik/test2
         imagePullPolicy: Always
         ports:
          - containerPort: 80
---

apiVersion: v1
kind: Service
metadata:
  name: test-service
  labels:
    app: test
spec:
  type: ClusterIP
  ports:
    - port: 4000
      targetPort: 80
      protocol: TCP
  selector:
    app: test
